### ISSUE TITLE
Seemingly no longer functional

### ISSUE THREAD

**Issue by imthehumanoid** [panicbit/simpla_vortaro_rs#2]
When I try to use the command it gives this error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This is only when searching for a specific word (as an argument), when not given correct arguments it still handles errors correctly.

**Comment by panicbit** [comment]
Nice to see that someone is using this :blush:.
I'll look into it!

**Comment by panicbit** [comment]
Are you using the latest version (0.4.1, check with `sv --version`)?
If not, can you please try again with the latest version?
And if it still doesn't work, can you give me the word that is failing?

**Comment by imthehumanoid** [comment]
Ah it seems I'm using a much older version, 0.1.0.
I'm using a program that installs software from github releases, and it apparently could only find 0.1.0, which is odd because the only one I can see on github is 0.2.0.
Not sure why I didn't notice that before, I'll probably just have to install it like a normal person, which I can never figure out how to do lol
My mistake!

**Comment by panicbit** [comment]
You probably had `0.2.0` then. It wrongly reports itself as `0.1.0` on the command line.

I'm not usually creating github releases, but I do usually tag versions at least.

The "normal" way to install this project is via `cargo install simpla_vortaro`.

**Comment by imthehumanoid** [comment]
After tweaking the location of the thing cargo downloads, I got it working
Thank you for pointing out the release is a bit outdated
I think I'm good now!

**Comment by panicbit** [comment]
Nice :)

I think I will automate release creation so that it's easier to use this project.

**Comment by panicbit** [comment]
Alright, I have managed to set up automatic releases :tada:
